variable "VPC_CIDR"                {}
variable "ENV"                     {}
variable "SUBNET_ZONES"            {}
variable "PUBLIC_SUBNETS_CIDR"     {}
variable "PRIVATE_SUBNETS_CIDR"    {}
variable "DEFAULT_VPC_ID"          {}
variable "DEFAULT_VPC_ROUTE_TABLE" {}
variable "DEFAULT_VPC_CIDR"        {}
variable "HOSTED_ZONE_ID"          {}